# Generated by Django 5.1.1 on 2024-09-12 12:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0002_faqcategory_slug_alter_faqcategory_icon_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="faqquestion",
            managers=[
                ("published2", django.db.models.manager.Manager()),
            ],
        ),
    ]
