repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.9'
    hooks:
       - id: bandit
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  