repos:
  # auto update
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: "v0.3.3post1"
    hooks:
      - id: pre-commit-update
        args: [--dry-run, --all-versions]

  # ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.1"
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]

  # django upgrade
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.20.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"]

  # bandit
  # - repo: https://github.com/PyCQA/bandit
  #   rev: "1.7.9"
  #   hooks:
  #     - id: bandit

  # black
  # - repo: https://github.com/psf/black
  #  rev: "24.4.1"
  #  hooks:
  #    - id: black

  # - repo: https://github.com/pycqa/flake8
  #  rev: 7.1.1
  #  hooks:
  #    - id: flake8
  #      args: [ "--ignore=E501,W503,F704,E203" ]

  # - repo: https://github.com/asottile/pyupgrade
  #  rev: v3.17.0
  #  hooks:
  #    - id: pyupgrade

  # - repo: https://github.com/pycqa/isort
  #  rev: 5.13.2
  #  hooks:
  #    - id: isort
  #      args: [ --profile=black ]

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.11.1"
  #  hooks:
  #    - id: mypy
  #      args: [ '--ignore-missing-imports', '--disable-error-code=top-level-await', "--disable-error-code=empty-body" ]
