# Generated by Django 5.1.1 on 2024-09-14 19:53

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=django_cryptography.fields.encrypt(
                models.DateField(blank=True, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=django_cryptography.fields.encrypt(
                models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")
            ),
        ),
    ]
