# Generated by Django 5.1.1 on 2024-09-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0002_alter_profile_bio_alter_profile_date_of_birth_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
