# Generated by Django 5.1.1 on 2024-09-14 22:53

import django.db.models.deletion
import django_cryptography.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "date_of_birth",
                    django_cryptography.fields.encrypt(
                        models.DateField(blank=True, null=True)
                    ),
                ),
                (
                    "photo",
                    django_cryptography.fields.encrypt(
                        models.ImageField(
                            blank=True, upload_to="users/%Y/%m/%d/"
                        )
                    ),
                ),
                (
                    "bio",
                    django_cryptography.fields.encrypt(
                        models.TextField(blank=True)
                    ),
                ),
                (
                    "email_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "forget_password_token",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
