# Generated by Django 5.1.1 on 2024-09-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email_token",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="forget_password_token",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
