from django.contrib.auth.decorators import login_required
from django.urls import path

from .views import (
    CustomDPClassificationView,
    CustomMLAnomalyView,
    MiscPagesView,
    PagesView,
)

app_name = "pages"

urlpatterns = [
    path(
        "pages/profile/user/",
        login_required(
            PagesView.as_view(template_name="pages/pages_profile_user.html")
        ),
        name="pages-profile-user",
    ),
    path(
        "pages/profile/teams/",
        login_required(
            PagesView.as_view(template_name="pages/pages_profile_teams.html")
        ),
        name="pages-profile-teams",
    ),
    path(
        "pages/profile/projects/",
        login_required(
            PagesView.as_view(template_name="pages/pages_profile_projects.html")
        ),
        name="pages-profile-projects",
    ),
    path(
        "pages/profile/connections/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_profile_connections.html"
            )
        ),
        name="pages-profile-connections",
    ),
    path(
        "pages/account_settings/account/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_account_settings_account.html"
            )
        ),
        name="pages-account-settings-account",
    ),
    path(
        "pages/account_settings/security/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_account_settings_security.html"
            )
        ),
        name="pages-account-settings-security",
    ),
    path(
        "pages/account_settings/notifications/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_account_settings_notifications.html"
            )
        ),
        name="pages-account-settings-notifications",
    ),
    path(
        "pages/account_settings/connections/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_account_settings_connections.html"
            )
        ),
        name="pages-account-settings-connections",
    ),
    path(
        "pages/faq/",
        login_required(PagesView.as_view(template_name="pages/pages_faq.html")),
        name="pages-faq",
    ),
    path(
        "pages/misc/error/",
        MiscPagesView.as_view(template_name="pages/pages_misc_error.html"),
        name="pages-misc-error",
    ),
    path(
        "pages/misc/under_maintenance/",
        MiscPagesView.as_view(
            template_name="pages/pages_misc_under_maintenance.html"
        ),
        name="pages-misc-under-maintenance",
    ),
    path(
        "pages/misc/comingsoon/",
        MiscPagesView.as_view(template_name="pages/pages_misc_comingsoon.html"),
        name="pages-misc-comingsoon",
    ),
    path(
        "pages/misc/not_authorized/",
        MiscPagesView.as_view(
            template_name="pages/pages_misc_not_authorized.html"
        ),
        name="pages-misc-not-authorized",
    ),
    path(
        "pages/machine_learning/classification/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_machine_learning_classification.html"
            )
        ),
        name="pages-machine-learning-classification",
    ),
    path(
        "pages/machine_learning/regression/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_machine_learning_regression.html"
            )
        ),
        name="pages-machine-learning-regression",
    ),
    path(
        "pages/machine_learning/time_series/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_machine_learning_time_series.html"
            )
        ),
        name="pages-machine-learning-time-series",
    ),
    path(
        "pages/machine_learning/clusturing/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_machine_learning_clustering.html"
            )
        ),
        name="pages-machine-learning-clustering",
    ),
    path(
        "pages/machine_learning/anomaly_detection/",
        login_required(CustomMLAnomalyView.as_view()),
        name="pages-machine-learning-anomaly-detection",
    ),
    path(
        "pages/deep_learning/classification/",
        login_required(CustomDPClassificationView.as_view()),
        name="pages-deep-learning-classification",
    ),
    path(
        "pages/deep_learning/segmentation/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_deep_learning_segmentation.html"
            )
        ),
        name="pages-deep-learning-segmentation",
    ),
    path(
        "pages/large_language_model/summarization/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_llm_summarization.html"
            )
        ),
        name="pages-llm-summarization",
    ),
    path(
        "pages/large_language_model/text_classification/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_llm_text_classification.html"
            )
        ),
        name="pages-llm-text-classification",
    ),
    path(
        "pages/large_language_model/text_generation/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_llm_text_generation.html"
            )
        ),
        name="pages-llm-text-generation",
    ),
    path(
        "pages/large_language_model/text_to_text_generation/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_llm_text_to_text_generation.html"
            )
        ),
        name="pages-llm-text-to-text-generation",
    ),
    path(
        "pages/large_language_model/token_classification/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_llm_token_classification.html"
            )
        ),
        name="pages-llm-token-classification",
    ),
    path(
        "pages/large_language_model/zero_shot_classification/",
        login_required(
            PagesView.as_view(
                template_name="pages/pages_llm_zero_shot_classification.html"
            )
        ),
        name="pages-llm-zero-shot-classification",
    ),
]
