name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
    - uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: 'pre commit fixes'